// Generated by CIRCT firtool-1.121.0
module csrGroup(	// src/main/scala/npc/regGroup/csrGroup.scala:9:7
  input         clock,	// src/main/scala/npc/regGroup/csrGroup.scala:9:7
                reset,	// src/main/scala/npc/regGroup/csrGroup.scala:9:7
  input  [11:0] io_csr,	// src/main/scala/npc/regGroup/csrGroup.scala:10:12
  input  [2:0]  io_opcode,	// src/main/scala/npc/regGroup/csrGroup.scala:10:12
  input         io_ecallIF,	// src/main/scala/npc/regGroup/csrGroup.scala:10:12
                io_mretIF,	// src/main/scala/npc/regGroup/csrGroup.scala:10:12
  input  [31:0] io_src1,	// src/main/scala/npc/regGroup/csrGroup.scala:10:12
                io_currentPC,	// src/main/scala/npc/regGroup/csrGroup.scala:10:12
  input         io_writeEnable,	// src/main/scala/npc/regGroup/csrGroup.scala:10:12
  output [31:0] io_csrData	// src/main/scala/npc/regGroup/csrGroup.scala:10:12
);

  reg  [31:0]      regGroup_0;	// src/main/scala/npc/regGroup/csrGroup.scala:24:25
  reg  [31:0]      regGroup_1;	// src/main/scala/npc/regGroup/csrGroup.scala:24:25
  reg  [31:0]      regGroup_2;	// src/main/scala/npc/regGroup/csrGroup.scala:24:25
  reg  [31:0]      regGroup_3;	// src/main/scala/npc/regGroup/csrGroup.scala:24:25
  wire [1:0]       targetCsr =
    io_csr == 12'h341 | io_mretIF
      ? 2'h0
      : io_csr == 12'h342
          ? 2'h1
          : io_csr == 12'h300 ? 2'h2 : {2{io_csr == 12'h305 | io_ecallIF}};	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/regGroup/csrGroup.scala:28:{12,29}, :29:12, :30:12, :31:{12,30}
  wire [3:0][31:0] _GEN = {{regGroup_3}, {regGroup_2}, {regGroup_1}, {regGroup_0}};	// src/main/scala/npc/regGroup/csrGroup.scala:24:25, :35:13
  always @(posedge clock) begin	// src/main/scala/npc/regGroup/csrGroup.scala:9:7
    if (reset) begin	// src/main/scala/npc/regGroup/csrGroup.scala:9:7
      regGroup_0 <= 32'h0;	// src/main/scala/npc/regGroup/csrGroup.scala:24:25
      regGroup_1 <= 32'h0;	// src/main/scala/npc/regGroup/csrGroup.scala:24:25
      regGroup_2 <= 32'h0;	// src/main/scala/npc/regGroup/csrGroup.scala:24:25
      regGroup_3 <= 32'h0;	// src/main/scala/npc/regGroup/csrGroup.scala:24:25
    end
    else begin	// src/main/scala/npc/regGroup/csrGroup.scala:9:7
      automatic logic [31:0] _regGroup_T_8;	// src/main/scala/chisel3/util/Mux.scala:126:16
      _regGroup_T_8 =
        io_opcode == 3'h1
          ? io_src1
          : io_opcode == 3'h2
              ? _GEN[targetCsr] | io_src1
              : ({32{io_opcode != 3'h3}} | ~io_src1) & _GEN[targetCsr];	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/regGroup/csrGroup.scala:35:13, :46:17, :47:{17,49}, :48:{17,52}
      if (io_ecallIF) begin	// src/main/scala/npc/regGroup/csrGroup.scala:10:12
        regGroup_0 <= io_currentPC;	// src/main/scala/npc/regGroup/csrGroup.scala:24:25
        regGroup_1 <= 32'hB;	// src/main/scala/npc/regGroup/csrGroup.scala:24:25
        regGroup_2 <= 32'h1800;	// src/main/scala/npc/regGroup/csrGroup.scala:24:25
      end
      else begin	// src/main/scala/npc/regGroup/csrGroup.scala:10:12
        if (io_writeEnable & targetCsr == 2'h0)	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/regGroup/csrGroup.scala:24:25, :43:30, :45:24
          regGroup_0 <= _regGroup_T_8;	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/regGroup/csrGroup.scala:24:25
        if (io_writeEnable & targetCsr == 2'h1)	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/regGroup/csrGroup.scala:24:25, :43:30, :45:24
          regGroup_1 <= _regGroup_T_8;	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/regGroup/csrGroup.scala:24:25
        if (io_writeEnable & targetCsr == 2'h2)	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/regGroup/csrGroup.scala:24:25, :43:30, :45:24
          regGroup_2 <= _regGroup_T_8;	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/regGroup/csrGroup.scala:24:25
      end
      if (io_ecallIF | ~(io_writeEnable & (&targetCsr))) begin	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/regGroup/csrGroup.scala:24:25, :38:19, :43:30, :45:24
      end
      else	// src/main/scala/npc/regGroup/csrGroup.scala:24:25, :38:19, :43:30
        regGroup_3 <= _regGroup_T_8;	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/regGroup/csrGroup.scala:24:25
    end
  end // always @(posedge)
  assign io_csrData = _GEN[targetCsr];	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/regGroup/csrGroup.scala:9:7, :35:13
endmodule

