// Generated by CIRCT firtool-1.121.0
module dataMemory(	// src/main/scala/npc/dataMemory/dataMemory.scala:6:7
  input  [31:0] io_targetAddr,	// src/main/scala/npc/dataMemory/dataMemory.scala:7:12
  input  [2:0]  io_funct3,	// src/main/scala/npc/dataMemory/dataMemory.scala:7:12
  input  [31:0] io_rs2,	// src/main/scala/npc/dataMemory/dataMemory.scala:7:12
  input         io_memWrite,	// src/main/scala/npc/dataMemory/dataMemory.scala:7:12
                io_memRead,	// src/main/scala/npc/dataMemory/dataMemory.scala:7:12
  output [31:0] io_readAddr,	// src/main/scala/npc/dataMemory/dataMemory.scala:7:12
  output        io_readType,	// src/main/scala/npc/dataMemory/dataMemory.scala:7:12
                io_readEnable,	// src/main/scala/npc/dataMemory/dataMemory.scala:7:12
  output [31:0] io_writeAddr,	// src/main/scala/npc/dataMemory/dataMemory.scala:7:12
                io_writeData,	// src/main/scala/npc/dataMemory/dataMemory.scala:7:12
  output        io_writeEnable,	// src/main/scala/npc/dataMemory/dataMemory.scala:7:12
  output [2:0]  io_byteNum	// src/main/scala/npc/dataMemory/dataMemory.scala:7:12
);

  wire _io_writeData_T = io_funct3 == 3'h0;	// src/main/scala/npc/dataMemory/dataMemory.scala:30:15
  wire _io_writeData_T_3 = io_funct3 == 3'h1;	// src/main/scala/npc/dataMemory/dataMemory.scala:31:15
  wire _io_writeData_T_6 = io_funct3 == 3'h2;	// src/main/scala/npc/dataMemory/dataMemory.scala:32:15
  assign io_readAddr = io_targetAddr;	// src/main/scala/npc/dataMemory/dataMemory.scala:6:7
  assign io_readType = io_funct3 < 3'h3;	// src/main/scala/npc/dataMemory/dataMemory.scala:6:7, :35:29
  assign io_readEnable = io_memRead;	// src/main/scala/npc/dataMemory/dataMemory.scala:6:7
  assign io_writeAddr = io_targetAddr;	// src/main/scala/npc/dataMemory/dataMemory.scala:6:7
  assign io_writeData =
    _io_writeData_T & io_memWrite
      ? {24'h0, io_rs2[7:0]}
      : _io_writeData_T_3 & io_memWrite
          ? {16'h0, io_rs2[15:0]}
          : _io_writeData_T_6 & io_memWrite ? io_rs2 : 32'h0;	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/dataMemory/dataMemory.scala:6:7, :30:15, :31:15, :32:15, :38:{22,47}, :39:{22,47}, :40:22
  assign io_writeEnable = io_memWrite;	// src/main/scala/npc/dataMemory/dataMemory.scala:6:7
  assign io_byteNum =
    _io_writeData_T | io_funct3 == 3'h4
      ? 3'h1
      : _io_writeData_T_3 | io_funct3 == 3'h5 ? 3'h2 : {_io_writeData_T_6, 2'h0};	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/dataMemory/dataMemory.scala:6:7, :30:{15,22,34}, :31:{15,22,34}, :32:15
endmodule

