// Generated by CIRCT firtool-1.121.0
module decoder(	// src/main/scala/npc/decoder/decoder.scala:7:7
  input  [6:0] io_opcode,	// src/main/scala/npc/decoder/decoder.scala:8:12
  input  [2:0] io_funct3,	// src/main/scala/npc/decoder/decoder.scala:8:12
  input  [6:0] io_funct7,	// src/main/scala/npc/decoder/decoder.scala:8:12
  input        io_zero,	// src/main/scala/npc/decoder/decoder.scala:8:12
               io_compareResult,	// src/main/scala/npc/decoder/decoder.scala:8:12
               io_systemDecoderResult_csrWrite,	// src/main/scala/npc/decoder/decoder.scala:8:12
  input  [2:0] io_systemDecoderResult_csrOpcode,	// src/main/scala/npc/decoder/decoder.scala:8:12
  input        io_systemDecoderResult_csrRead,	// src/main/scala/npc/decoder/decoder.scala:8:12
               io_systemDecoderResult_ebreakIF,	// src/main/scala/npc/decoder/decoder.scala:8:12
               io_systemDecoderResult_ecallIF,	// src/main/scala/npc/decoder/decoder.scala:8:12
               io_systemDecoderResult_mretIF,	// src/main/scala/npc/decoder/decoder.scala:8:12
  output       io_regWrite,	// src/main/scala/npc/decoder/decoder.scala:8:12
  output [2:0] io_regWriteType,	// src/main/scala/npc/decoder/decoder.scala:8:12
  output       io_memWrite,	// src/main/scala/npc/decoder/decoder.scala:8:12
               io_memRead,	// src/main/scala/npc/decoder/decoder.scala:8:12
  output [2:0] io_immType,	// src/main/scala/npc/decoder/decoder.scala:8:12
  output [1:0] io_pcNextType,	// src/main/scala/npc/decoder/decoder.scala:8:12
  output       io_pcAluSrc,	// src/main/scala/npc/decoder/decoder.scala:8:12
               io_aluSrc,	// src/main/scala/npc/decoder/decoder.scala:8:12
  output [3:0] io_aluOp,	// src/main/scala/npc/decoder/decoder.scala:8:12
  output       io_systemInstCtrl_csrWrite,	// src/main/scala/npc/decoder/decoder.scala:8:12
  output [2:0] io_systemInstCtrl_csrOpcode,	// src/main/scala/npc/decoder/decoder.scala:8:12
  output       io_systemInstCtrl_ebreakIF,	// src/main/scala/npc/decoder/decoder.scala:8:12
               io_systemInstCtrl_ecallIF,	// src/main/scala/npc/decoder/decoder.scala:8:12
               io_systemInstCtrl_mretIF	// src/main/scala/npc/decoder/decoder.scala:8:12
);

  wire       _GEN = io_opcode == 7'h33;	// src/main/scala/npc/decoder/decoder.scala:52:21
  wire       _GEN_0 = io_opcode == 7'h13;	// src/main/scala/npc/decoder/decoder.scala:52:21
  wire       _GEN_1 = io_opcode == 7'h3;	// src/main/scala/npc/decoder/decoder.scala:52:21
  wire       _GEN_2 = _GEN | _GEN_0;	// src/main/scala/npc/decoder/decoder.scala:32:14, :52:21
  wire       _GEN_3 = io_opcode == 7'h23;	// src/main/scala/npc/decoder/decoder.scala:52:21
  wire       _GEN_4 = _GEN_0 | _GEN_1;	// src/main/scala/npc/decoder/decoder.scala:31:15, :52:21
  wire       _GEN_5 = _GEN | _GEN_4;	// src/main/scala/npc/decoder/decoder.scala:31:15, :52:21
  wire       _GEN_6 = io_opcode == 7'h63;	// src/main/scala/npc/decoder/decoder.scala:52:21
  wire       _GEN_7 = _GEN_1 | _GEN_3;	// src/main/scala/npc/decoder/decoder.scala:52:21, :77:15, :84:15
  wire       _io_pcNextType_T_9 = (&io_funct3) & ~io_compareResult;	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/decoder/decoder.scala:95:30, :97:19
  wire [7:0] _GEN_8 =
    {{_io_pcNextType_T_9},
     {io_compareResult},
     {~io_compareResult},
     {io_compareResult},
     {_io_pcNextType_T_9},
     {_io_pcNextType_T_9},
     {~io_zero},
     {io_zero}};	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/decoder/decoder.scala:92:19, :93:{19,30}, :94:19, :95:{19,30}, :96:19
  wire       _GEN_9 = io_opcode == 7'h6F;	// src/main/scala/npc/decoder/decoder.scala:52:21
  wire       _GEN_10 = io_opcode == 7'h67;	// src/main/scala/npc/decoder/decoder.scala:52:21
  wire       _GEN_11 = io_opcode == 7'h37;	// src/main/scala/npc/decoder/decoder.scala:52:21
  wire       _GEN_12 = io_opcode == 7'h17;	// src/main/scala/npc/decoder/decoder.scala:52:21
  wire       _GEN_13 = io_opcode == 7'h73;	// src/main/scala/npc/decoder/decoder.scala:52:21
  wire       _GEN_14 = _GEN_11 | _GEN_12;	// src/main/scala/npc/decoder/decoder.scala:52:21, :119:19, :125:19
  wire       _GEN_15 = _GEN_9 | _GEN_10 | _GEN_14;	// src/main/scala/npc/decoder/decoder.scala:52:21, :103:19, :111:19, :119:19, :125:19
  wire       _GEN_16 = _GEN_3 | _GEN_6;	// src/main/scala/npc/decoder/decoder.scala:29:15, :52:21
  wire       _GEN_17 = _GEN_9 | _GEN_10;	// src/main/scala/npc/decoder/decoder.scala:52:21, :104:22, :112:22
  wire       _GEN_18 = _GEN | _GEN_0 | _GEN_1 | _GEN_3 | _GEN_6 | _GEN_15;	// src/main/scala/npc/decoder/decoder.scala:38:21, :52:21, :103:19, :111:19, :119:19, :125:19
  assign io_regWrite =
    _GEN_5 | ~_GEN_16 & (_GEN_15 | _GEN_13 & io_systemDecoderResult_csrRead);	// src/main/scala/npc/decoder/decoder.scala:7:7, :29:15, :31:15, :52:21, :54:19, :61:19, :72:19, :103:19, :111:19, :119:19, :125:19, :133:18
  assign io_regWriteType =
    _GEN_2
      ? 3'h0
      : _GEN_1
          ? 3'h1
          : _GEN_16
              ? 3'h0
              : _GEN_17
                  ? 3'h2
                  : _GEN_11
                      ? 3'h3
                      : _GEN_12
                          ? 3'h4
                          : _GEN_13 & io_systemDecoderResult_csrRead ? 3'h5 : 3'h0;	// src/main/scala/npc/decoder/decoder.scala:7:7, :29:15, :30:18, :32:14, :52:21, :55:23, :62:23, :66:19, :74:22, :104:22, :112:22, :120:23, :126:23, :134:{22,27}
  assign io_memWrite = ~_GEN_5 & _GEN_3;	// src/main/scala/npc/decoder/decoder.scala:7:7, :31:15, :52:21
  assign io_memRead = ~_GEN_2 & _GEN_1;	// src/main/scala/npc/decoder/decoder.scala:7:7, :32:14, :52:21
  assign io_immType =
    _GEN
      ? 3'h0
      : _GEN_4
          ? 3'h1
          : _GEN_3
              ? 3'h2
              : _GEN_6
                  ? 3'h3
                  : _GEN_9 ? 3'h5 : _GEN_10 ? 3'h1 : _GEN_14 ? 3'h4 : {2'h0, _GEN_13};	// src/main/scala/npc/decoder/decoder.scala:7:7, :31:15, :33:15, :52:21, :63:19, :66:19, :75:19, :82:19, :90:17, :107:19, :115:19, :119:19, :121:19, :125:19, :127:19, :135:19
  assign io_pcNextType =
    _GEN | _GEN_0 | _GEN_7
      ? 2'h0
      : _GEN_6
          ? {1'h0, _GEN_8[io_funct3]}
          : _GEN_17
              ? 2'h1
              : _GEN_14
                  ? 2'h0
                  : {_GEN_13
                       & (io_systemDecoderResult_ecallIF | io_systemDecoderResult_mretIF),
                     1'h0};	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/decoder/decoder.scala:7:7, :34:17, :52:21, :77:15, :84:15, :91:20, :92:19, :93:19, :94:19, :95:19, :96:19, :104:22, :105:22, :112:22, :113:21, :119:19, :125:19, :138:{20,25,57}
  assign io_pcAluSrc =
    _GEN | _GEN_0 | _GEN_1 | _GEN_3 | _GEN_6 | _GEN_9 | io_opcode != 7'h67;	// src/main/scala/npc/decoder/decoder.scala:7:7, :35:15, :52:21, :99:18, :106:19, :114:19
  assign io_aluSrc = ~_GEN & (_GEN_4 | _GEN_3);	// src/main/scala/npc/decoder/decoder.scala:7:7, :31:15, :52:21, :56:19, :64:19, :76:16
  assign io_aluOp =
    _GEN
      ? {io_funct3, io_funct7[5]}
      : _GEN_0
          ? {io_funct3, (io_funct3 == 3'h1 | io_funct3 == 3'h5) & io_funct7[5]}
          : _GEN_7 | ~_GEN_6 ? 4'h0 : {2'h1, &(io_funct3[2:1]), 1'h0};	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/decoder/decoder.scala:7:7, :52:21, :57:{19,32,44}, :65:{19,40}, :66:{19,52,64}, :67:{19,53}, :77:15, :84:15, :89:{15,30}
  assign io_systemInstCtrl_csrWrite =
    ~_GEN_18 & _GEN_13 & io_systemDecoderResult_csrWrite;	// src/main/scala/npc/decoder/decoder.scala:7:7, :38:21, :52:21, :139:24
  assign io_systemInstCtrl_csrOpcode =
    _GEN_18 | ~_GEN_13 ? 3'h0 : io_systemDecoderResult_csrOpcode;	// src/main/scala/npc/decoder/decoder.scala:7:7, :38:21, :52:21
  assign io_systemInstCtrl_ebreakIF =
    ~_GEN_18 & _GEN_13 & io_systemDecoderResult_ebreakIF;	// src/main/scala/npc/decoder/decoder.scala:7:7, :38:21, :52:21, :139:24
  assign io_systemInstCtrl_ecallIF = ~_GEN_18 & _GEN_13 & io_systemDecoderResult_ecallIF;	// src/main/scala/npc/decoder/decoder.scala:7:7, :38:21, :52:21, :139:24
  assign io_systemInstCtrl_mretIF = ~_GEN_18 & _GEN_13 & io_systemDecoderResult_mretIF;	// src/main/scala/npc/decoder/decoder.scala:7:7, :38:21, :52:21, :139:24
endmodule

