// Generated by CIRCT firtool-1.121.0
module decoder(	// src/main/scala/npc/decoder/decoder.scala:6:7
  input  [6:0] io_opcode,	// src/main/scala/npc/decoder/decoder.scala:7:12
  input  [2:0] io_funct3,	// src/main/scala/npc/decoder/decoder.scala:7:12
  input  [6:0] io_funct7,	// src/main/scala/npc/decoder/decoder.scala:7:12
  input        io_zero,	// src/main/scala/npc/decoder/decoder.scala:7:12
               io_compareResult,	// src/main/scala/npc/decoder/decoder.scala:7:12
  output       io_regWrite,	// src/main/scala/npc/decoder/decoder.scala:7:12
  output [2:0] io_regWriteType,	// src/main/scala/npc/decoder/decoder.scala:7:12
  output       io_memWrite,	// src/main/scala/npc/decoder/decoder.scala:7:12
               io_memRead,	// src/main/scala/npc/decoder/decoder.scala:7:12
  output [2:0] io_immType,	// src/main/scala/npc/decoder/decoder.scala:7:12
  output       io_pcIF,	// src/main/scala/npc/decoder/decoder.scala:7:12
               io_pcAluSrc,	// src/main/scala/npc/decoder/decoder.scala:7:12
               io_aluSrc,	// src/main/scala/npc/decoder/decoder.scala:7:12
  output [3:0] io_aluOp,	// src/main/scala/npc/decoder/decoder.scala:7:12
  output       io_finishIF	// src/main/scala/npc/decoder/decoder.scala:7:12
);

  wire       _GEN = io_opcode == 7'h33;	// src/main/scala/npc/decoder/decoder.scala:50:21
  wire       _GEN_0 = io_opcode == 7'h13;	// src/main/scala/npc/decoder/decoder.scala:50:21
  wire       _GEN_1 = io_opcode == 7'h3;	// src/main/scala/npc/decoder/decoder.scala:50:21
  wire       _GEN_2 = _GEN | _GEN_0;	// src/main/scala/npc/decoder/decoder.scala:30:14, :50:21
  wire       _GEN_3 = io_opcode == 7'h23;	// src/main/scala/npc/decoder/decoder.scala:50:21
  wire       _GEN_4 = _GEN_0 | _GEN_1;	// src/main/scala/npc/decoder/decoder.scala:29:15, :50:21
  wire       _GEN_5 = _GEN | _GEN_4;	// src/main/scala/npc/decoder/decoder.scala:29:15, :50:21
  wire       _GEN_6 = io_opcode == 7'h63;	// src/main/scala/npc/decoder/decoder.scala:50:21
  wire       _GEN_7 = _GEN_1 | _GEN_3;	// src/main/scala/npc/decoder/decoder.scala:50:21, :75:15, :82:15
  wire       _io_pcIF_T_9 = (&io_funct3) & ~io_compareResult;	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/decoder/decoder.scala:93:30, :95:19
  wire [7:0] _GEN_8 =
    {{_io_pcIF_T_9},
     {io_compareResult},
     {~io_compareResult},
     {io_compareResult},
     {_io_pcIF_T_9},
     {_io_pcIF_T_9},
     {~io_zero},
     {io_zero}};	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/decoder/decoder.scala:90:19, :91:{19,30}, :92:19, :93:{19,30}, :94:19
  wire       _GEN_9 = io_opcode == 7'h6F;	// src/main/scala/npc/decoder/decoder.scala:50:21
  wire       _GEN_10 = io_opcode == 7'h67;	// src/main/scala/npc/decoder/decoder.scala:50:21
  wire       _GEN_11 = io_opcode == 7'h37;	// src/main/scala/npc/decoder/decoder.scala:50:21
  wire       _GEN_12 = io_opcode == 7'h17;	// src/main/scala/npc/decoder/decoder.scala:50:21
  wire       _GEN_13 = _GEN_3 | _GEN_6;	// src/main/scala/npc/decoder/decoder.scala:27:15, :50:21
  wire       _GEN_14 = _GEN_11 | _GEN_12;	// src/main/scala/npc/decoder/decoder.scala:31:15, :50:21, :119:19, :125:19
  assign io_regWrite = _GEN_5 | ~_GEN_13 & (_GEN_9 | _GEN_10 | _GEN_11 | _GEN_12);	// src/main/scala/npc/decoder/decoder.scala:6:7, :27:15, :29:15, :50:21, :52:19, :59:19, :70:19, :101:19, :109:19, :117:19
  assign io_regWriteType =
    _GEN_2
      ? 3'h0
      : _GEN_1
          ? 3'h1
          : _GEN_13 ? 3'h0 : _GEN_9 | _GEN_10 ? 3'h2 : _GEN_11 ? 3'h3 : {_GEN_12, 2'h0};	// src/main/scala/npc/decoder/decoder.scala:6:7, :27:15, :28:18, :30:14, :50:21, :53:23, :60:23, :64:19, :72:22, :102:22, :110:22, :118:23, :124:23
  assign io_memWrite = ~_GEN_5 & _GEN_3;	// src/main/scala/npc/decoder/decoder.scala:6:7, :29:15, :50:21
  assign io_memRead = ~_GEN_2 & _GEN_1;	// src/main/scala/npc/decoder/decoder.scala:6:7, :30:14, :50:21
  assign io_immType =
    _GEN
      ? 3'h0
      : _GEN_4
          ? 3'h1
          : _GEN_3
              ? 3'h2
              : _GEN_6 ? 3'h3 : _GEN_9 ? 3'h5 : _GEN_10 ? 3'h1 : {_GEN_14, 2'h0};	// src/main/scala/npc/decoder/decoder.scala:6:7, :29:15, :31:15, :50:21, :61:19, :64:19, :73:19, :80:19, :88:17, :105:19, :113:19, :119:19, :125:19
  assign io_pcIF =
    ~(_GEN | _GEN_0 | _GEN_7) & (_GEN_6 ? _GEN_8[io_funct3] : _GEN_9 | _GEN_10);	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/decoder/decoder.scala:6:7, :32:15, :50:21, :75:15, :82:15, :89:14, :90:19, :91:19, :92:19, :93:19, :94:19, :103:19
  assign io_pcAluSrc =
    _GEN | _GEN_0 | _GEN_1 | _GEN_3 | _GEN_6 | _GEN_9 | io_opcode != 7'h67;	// src/main/scala/npc/decoder/decoder.scala:6:7, :33:15, :50:21, :97:18, :104:19, :112:19
  assign io_aluSrc = ~_GEN & (_GEN_4 | _GEN_3);	// src/main/scala/npc/decoder/decoder.scala:6:7, :29:15, :50:21, :54:19, :62:19, :74:16
  assign io_aluOp =
    _GEN
      ? {io_funct3, io_funct7[5]}
      : _GEN_0
          ? {io_funct3, (io_funct3 == 3'h1 | io_funct3 == 3'h5) & io_funct7[5]}
          : _GEN_7 | ~_GEN_6 ? 4'h0 : {2'h1, &(io_funct3[2:1]), 1'h0};	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/decoder/decoder.scala:6:7, :50:21, :55:{19,32,44}, :63:{19,40}, :64:{19,52,64}, :65:{19,53}, :75:15, :82:15, :87:{15,30}
  assign io_finishIF =
    ~(_GEN | _GEN_0 | _GEN_1 | _GEN_3 | _GEN_6 | _GEN_9 | _GEN_10 | _GEN_14)
    & io_opcode == 7'h73;	// src/main/scala/npc/decoder/decoder.scala:6:7, :31:15, :36:15, :50:21, :119:19, :125:19
endmodule

