// Generated by CIRCT firtool-1.121.0
// 结束模块
module finishSim (
    input finishStatus,
    input clock,
    input reset
);
    always @(posedge clock) begin
        if(finishStatus) begin
            $display("End the simulation!");
            $finish;
        end
    end
endmodule