// Generated by CIRCT firtool-1.121.0
module immExtender(	// src/main/scala/npc/immExtender/immExtender.scala:6:7
  input  [31:0] io_inst,	// src/main/scala/npc/immExtender/immExtender.scala:13:12
  input  [2:0]  io_immType,	// src/main/scala/npc/immExtender/immExtender.scala:13:12
  output [31:0] io_immSrc	// src/main/scala/npc/immExtender/immExtender.scala:13:12
);

  wire [20:0] _io_immSrc_T_26 =
    io_immType == 3'h5
      ? {io_inst[31], io_inst[19:12], io_inst[20], io_inst[30:21], 1'h0}
      : 21'h0;	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/immExtender/immExtender.scala:9:36, :11:{31,45,57,66}, :25:17
  wire [19:0] _GEN = {20{io_inst[31]}};	// src/main/scala/chisel3/util/Mux.scala:126:16
  assign io_immSrc =
    io_immType == 3'h1
      ? {_GEN, io_inst[31:20]}
      : io_immType == 3'h2
          ? {_GEN, io_inst[31:25], io_inst[11:7]}
          : io_immType == 3'h3
              ? {{20{io_inst[31]}}, io_inst[7], io_inst[30:25], io_inst[11:8], 1'h0}
              : io_immType == 3'h4
                  ? {io_inst[31:12], 12'h0}
                  : {{11{_io_immSrc_T_26[20]}}, _io_immSrc_T_26};	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/immExtender/immExtender.scala:6:7, :7:32, :8:{36,48}, :9:{36,45,53,65}, :10:{31,36}, :21:17, :22:17, :23:17, :24:17
endmodule

