// Generated by CIRCT firtool-1.121.0
module multALU(	// src/main/scala/npc/ALU/multALU.scala:22:7
  input  [31:0] io_a,	// src/main/scala/npc/ALU/multALU.scala:24:14
                io_b,	// src/main/scala/npc/ALU/multALU.scala:24:14
  input  [3:0]  io_opcode,	// src/main/scala/npc/ALU/multALU.scala:24:14
  output [31:0] io_out,	// src/main/scala/npc/ALU/multALU.scala:24:14
  output        io_zero	// src/main/scala/npc/ALU/multALU.scala:24:14
);

  wire        _aluSeq_31_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_30_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_30_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_29_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_29_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_28_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_28_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_27_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_27_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_26_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_26_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_25_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_25_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_24_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_24_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_23_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_23_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_22_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_22_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_21_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_21_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_20_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_20_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_19_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_19_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_18_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_18_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_17_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_17_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_16_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_16_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_15_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_15_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_14_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_14_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_13_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_13_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_12_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_12_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_11_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_11_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_10_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_10_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_9_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_9_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_8_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_8_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_7_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_7_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_6_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_6_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_5_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_5_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_4_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_4_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_3_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_3_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_2_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_2_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_1_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_1_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_0_singleALUIO_s;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire        _aluSeq_0_singleALUIO_cout;	// src/main/scala/npc/ALU/multALU.scala:38:11
  wire [31:0] inputB = io_opcode == 4'h0 ? io_b : 32'h0 - io_b;	// src/main/scala/npc/ALU/multALU.scala:42:{19,30,45}
  wire [31:0] outWire =
    {_aluSeq_31_singleALUIO_s,
     _aluSeq_30_singleALUIO_s,
     _aluSeq_29_singleALUIO_s,
     _aluSeq_28_singleALUIO_s,
     _aluSeq_27_singleALUIO_s,
     _aluSeq_26_singleALUIO_s,
     _aluSeq_25_singleALUIO_s,
     _aluSeq_24_singleALUIO_s,
     _aluSeq_23_singleALUIO_s,
     _aluSeq_22_singleALUIO_s,
     _aluSeq_21_singleALUIO_s,
     _aluSeq_20_singleALUIO_s,
     _aluSeq_19_singleALUIO_s,
     _aluSeq_18_singleALUIO_s,
     _aluSeq_17_singleALUIO_s,
     _aluSeq_16_singleALUIO_s,
     _aluSeq_15_singleALUIO_s,
     _aluSeq_14_singleALUIO_s,
     _aluSeq_13_singleALUIO_s,
     _aluSeq_12_singleALUIO_s,
     _aluSeq_11_singleALUIO_s,
     _aluSeq_10_singleALUIO_s,
     _aluSeq_9_singleALUIO_s,
     _aluSeq_8_singleALUIO_s,
     _aluSeq_7_singleALUIO_s,
     _aluSeq_6_singleALUIO_s,
     _aluSeq_5_singleALUIO_s,
     _aluSeq_4_singleALUIO_s,
     _aluSeq_3_singleALUIO_s,
     _aluSeq_2_singleALUIO_s,
     _aluSeq_1_singleALUIO_s,
     _aluSeq_0_singleALUIO_s};	// src/main/scala/npc/ALU/multALU.scala:38:11, :57:17
  wire [62:0] _io_out_T_1 = {{31{io_a[31]}}, io_a} << io_b[4:0];	// src/main/scala/npc/ALU/multALU.scala:67:{23,30}
  singleALU aluSeq_0 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[0]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[0]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (1'h0),
    .singleALUIO_s    (_aluSeq_0_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_0_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_1 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[1]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[1]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_0_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_1_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_1_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_2 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[2]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[2]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_1_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_2_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_2_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_3 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[3]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[3]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_2_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_3_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_3_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_4 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[4]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[4]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_3_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_4_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_4_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_5 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[5]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[5]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_4_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_5_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_5_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_6 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[6]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[6]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_5_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_6_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_6_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_7 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[7]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[7]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_6_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_7_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_7_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_8 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[8]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[8]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_7_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_8_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_8_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_9 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[9]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[9]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_8_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_9_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_9_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_10 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[10]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[10]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_9_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_10_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_10_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_11 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[11]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[11]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_10_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_11_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_11_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_12 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[12]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[12]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_11_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_12_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_12_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_13 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[13]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[13]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_12_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_13_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_13_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_14 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[14]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[14]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_13_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_14_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_14_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_15 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[15]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[15]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_14_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_15_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_15_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_16 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[16]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[16]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_15_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_16_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_16_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_17 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[17]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[17]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_16_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_17_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_17_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_18 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[18]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[18]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_17_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_18_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_18_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_19 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[19]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[19]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_18_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_19_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_19_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_20 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[20]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[20]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_19_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_20_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_20_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_21 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[21]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[21]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_20_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_21_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_21_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_22 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[22]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[22]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_21_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_22_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_22_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_23 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[23]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[23]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_22_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_23_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_23_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_24 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[24]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[24]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_23_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_24_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_24_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_25 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[25]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[25]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_24_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_25_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_25_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_26 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[26]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[26]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_25_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_26_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_26_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_27 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[27]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[27]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_26_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_27_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_27_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_28 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[28]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[28]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_27_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_28_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_28_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_29 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[29]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[29]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_28_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_29_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_29_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_30 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[30]),	// src/main/scala/npc/ALU/multALU.scala:46:36
    .singleALUIO_b    (inputB[30]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :47:38
    .singleALUIO_cin  (_aluSeq_29_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_30_singleALUIO_s),
    .singleALUIO_cout (_aluSeq_30_singleALUIO_cout)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  singleALU aluSeq_31 (	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_a    (io_a[31]),	// src/main/scala/npc/ALU/multALU.scala:51:36
    .singleALUIO_b    (inputB[31]),	// src/main/scala/npc/ALU/multALU.scala:42:19, :52:38
    .singleALUIO_cin  (_aluSeq_30_singleALUIO_cout),	// src/main/scala/npc/ALU/multALU.scala:38:11
    .singleALUIO_s    (_aluSeq_31_singleALUIO_s),
    .singleALUIO_cout (/* unused */)
  );	// src/main/scala/npc/ALU/multALU.scala:38:11
  assign io_out =
    io_opcode == 4'h2
      ? _io_out_T_1[31:0]
      : io_opcode == 4'h4
          ? {31'h0, $signed(io_a) < $signed(io_b)}
          : io_opcode == 4'h6
              ? {31'h0, io_a < io_b}
              : io_opcode == 4'h8
                  ? io_a ^ io_b
                  : io_opcode == 4'hA
                      ? io_a >> io_b[4:0]
                      : io_opcode == 4'hB
                          ? $signed($signed(io_a) >>> io_b[4:0])
                          : io_opcode == 4'hC
                              ? io_a | io_b
                              : io_opcode == 4'hE ? io_a & io_b : outWire;	// src/main/scala/npc/ALU/multALU.scala:22:7, :57:17, :62:9, :65:21, :67:{14,23,37}, :73:{14,26}, :78:{14,33}, :83:{14,23}, :88:{14,30,37}, :93:{14,23,30}, :98:{14,23}, :103:{14,23}
  assign io_zero = outWire == 32'h0;	// src/main/scala/npc/ALU/multALU.scala:22:7, :57:17, :59:23
endmodule

