// Generated by CIRCT firtool-1.121.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module npc(	// src/main/scala/npc/npc.scala:14:7
  input         clock,	// src/main/scala/npc/npc.scala:14:7
                reset,	// src/main/scala/npc/npc.scala:14:7
  output [31:0] io_readAddr,	// src/main/scala/npc/npc.scala:18:12
  output        io_readType,	// src/main/scala/npc/npc.scala:18:12
  input  [31:0] io_readData,	// src/main/scala/npc/npc.scala:18:12
  output        io_readEnable,	// src/main/scala/npc/npc.scala:18:12
  output [31:0] io_writeAddr,	// src/main/scala/npc/npc.scala:18:12
                io_writeData,	// src/main/scala/npc/npc.scala:18:12
  output        io_writeEnable,	// src/main/scala/npc/npc.scala:18:12
  output [2:0]  io_byteNum,	// src/main/scala/npc/npc.scala:18:12
  output [31:0] io_pc,	// src/main/scala/npc/npc.scala:18:12
  input  [31:0] io_inst	// src/main/scala/npc/npc.scala:18:12
);

  wire [31:0]      _immExtender_io_immSrc;	// src/main/scala/npc/npc.scala:43:25
  wire [31:0]      _pcALU_io_out;	// src/main/scala/npc/npc.scala:42:19
  wire [31:0]      _mainALU_io_out;	// src/main/scala/npc/npc.scala:41:21
  wire             _mainALU_io_zero;	// src/main/scala/npc/npc.scala:41:21
  wire             _decoder_io_regWrite;	// src/main/scala/npc/npc.scala:40:21
  wire [2:0]       _decoder_io_regWriteType;	// src/main/scala/npc/npc.scala:40:21
  wire             _decoder_io_memWrite;	// src/main/scala/npc/npc.scala:40:21
  wire             _decoder_io_memRead;	// src/main/scala/npc/npc.scala:40:21
  wire [2:0]       _decoder_io_immType;	// src/main/scala/npc/npc.scala:40:21
  wire             _decoder_io_pcIF;	// src/main/scala/npc/npc.scala:40:21
  wire             _decoder_io_pcAluSrc;	// src/main/scala/npc/npc.scala:40:21
  wire             _decoder_io_aluSrc;	// src/main/scala/npc/npc.scala:40:21
  wire [3:0]       _decoder_io_aluOp;	// src/main/scala/npc/npc.scala:40:21
  wire             _decoder_io_finishIF;	// src/main/scala/npc/npc.scala:40:21
  wire [31:0]      _gpr_io_rs1Data;	// src/main/scala/npc/npc.scala:38:17
  wire [31:0]      _gpr_io_rs2Data;	// src/main/scala/npc/npc.scala:38:17
  reg  [31:0]      pcReg;	// src/main/scala/npc/npc.scala:37:20
  wire [31:0]      _pcReg_T = pcReg + 32'h4;	// src/main/scala/npc/npc.scala:37:20, :107:55
  wire [7:0][31:0] _GEN =
    {{32'h0},
     {32'h0},
     {32'h0},
     {_pcALU_io_out},
     {_immExtender_io_immSrc},
     {_pcReg_T},
     {io_readData},
     {_mainALU_io_out}};	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/npc.scala:41:21, :42:19, :43:25, :105:29, :106:29, :107:{29,55}, :108:29, :109:29
  wire [31:0]      gpr_io_writeData = _GEN[_decoder_io_regWriteType];	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/npc.scala:40:21, :105:29, :106:29, :107:29, :108:29, :109:29
  `ifndef SYNTHESIS	// src/main/scala/npc/npc.scala:121:9
    always @(posedge clock) begin	// src/main/scala/npc/npc.scala:121:9
      if ((`PRINTF_COND_) & ~reset) begin	// src/main/scala/npc/npc.scala:121:9, :124:9
        $fwrite(32'h80000002, "pc = 0x%x inst = 0x%x\n", pcReg, io_inst);	// src/main/scala/npc/npc.scala:37:20, :121:9
        $fwrite(32'h80000002,
                "gprWriteTarget = %d gprWriteData = 0x%x gprWriteEnable = %d\n",
                io_inst[10:7], gpr_io_writeData, _decoder_io_regWrite);	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/npc.scala:40:21, :52:{12,21}, :122:9
        $fwrite(32'h80000002, "regWriteType = %d, aluOp = %d, aluSrc = %d\n",
                _decoder_io_regWriteType, _decoder_io_aluOp, _decoder_io_aluSrc);	// src/main/scala/npc/npc.scala:40:21, :123:9
        $fwrite(32'h80000002, "immType = %d, imm = 0x%x, pcALU.out = 0x%x\n",
                _decoder_io_immType, _immExtender_io_immSrc, _pcALU_io_out);	// src/main/scala/npc/npc.scala:40:21, :42:19, :43:25, :124:9
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// src/main/scala/npc/npc.scala:14:7
    if (reset)	// src/main/scala/npc/npc.scala:14:7
      pcReg <= 32'h80000000;	// src/main/scala/npc/npc.scala:37:20
    else	// src/main/scala/npc/npc.scala:14:7
      pcReg <= _decoder_io_pcIF ? _pcALU_io_out : _pcReg_T;	// src/main/scala/npc/npc.scala:37:20, :40:21, :42:19, :107:55, :114:13
  end // always @(posedge)
  regGroup gpr (	// src/main/scala/npc/npc.scala:38:17
    .clock          (clock),
    .reset          (reset),
    .io_rs1         (io_inst[18:15]),	// src/main/scala/npc/npc.scala:54:{13,22}
    .io_rs2         (io_inst[23:20]),	// src/main/scala/npc/npc.scala:55:{13,22}
    .io_rd          (io_inst[10:7]),	// src/main/scala/npc/npc.scala:52:{12,21}
    .io_writeData   (gpr_io_writeData),	// src/main/scala/chisel3/util/Mux.scala:126:16
    .io_writeEnable (_decoder_io_regWrite),	// src/main/scala/npc/npc.scala:40:21
    .io_rs1Data     (_gpr_io_rs1Data),
    .io_rs2Data     (_gpr_io_rs2Data)
  );	// src/main/scala/npc/npc.scala:38:17
  dataMemory mem (	// src/main/scala/npc/npc.scala:39:17
    .io_targetAddr  (_mainALU_io_out),	// src/main/scala/npc/npc.scala:41:21
    .io_funct3      (io_inst[14:12]),	// src/main/scala/npc/npc.scala:48:21
    .io_rs2         (_gpr_io_rs2Data),	// src/main/scala/npc/npc.scala:38:17
    .io_memWrite    (_decoder_io_memWrite),	// src/main/scala/npc/npc.scala:40:21
    .io_memRead     (_decoder_io_memRead),	// src/main/scala/npc/npc.scala:40:21
    .io_readAddr    (io_readAddr),
    .io_readType    (io_readType),
    .io_readEnable  (io_readEnable),
    .io_writeAddr   (io_writeAddr),
    .io_writeData   (io_writeData),
    .io_writeEnable (io_writeEnable),
    .io_byteNum     (io_byteNum)
  );	// src/main/scala/npc/npc.scala:39:17
  decoder decoder (	// src/main/scala/npc/npc.scala:40:21
    .io_opcode        (io_inst[6:0]),	// src/main/scala/npc/npc.scala:47:21
    .io_funct3        (io_inst[14:12]),	// src/main/scala/npc/npc.scala:48:21
    .io_funct7        (io_inst[31:25]),	// src/main/scala/npc/npc.scala:49:21
    .io_zero          (_mainALU_io_zero),	// src/main/scala/npc/npc.scala:41:21
    .io_compareResult (_mainALU_io_out[0]),	// src/main/scala/npc/npc.scala:41:21, :79:43
    .io_regWrite      (_decoder_io_regWrite),
    .io_regWriteType  (_decoder_io_regWriteType),
    .io_memWrite      (_decoder_io_memWrite),
    .io_memRead       (_decoder_io_memRead),
    .io_immType       (_decoder_io_immType),
    .io_pcIF          (_decoder_io_pcIF),
    .io_pcAluSrc      (_decoder_io_pcAluSrc),
    .io_aluSrc        (_decoder_io_aluSrc),
    .io_aluOp         (_decoder_io_aluOp),
    .io_finishIF      (_decoder_io_finishIF)
  );	// src/main/scala/npc/npc.scala:40:21
  multALU mainALU (	// src/main/scala/npc/npc.scala:41:21
    .io_a      (_gpr_io_rs1Data),	// src/main/scala/npc/npc.scala:38:17
    .io_b      (_decoder_io_aluSrc ? _immExtender_io_immSrc : _gpr_io_rs2Data),	// src/main/scala/npc/npc.scala:38:17, :40:21, :43:25, :73:20
    .io_opcode (_decoder_io_aluOp),	// src/main/scala/npc/npc.scala:40:21
    .io_out    (_mainALU_io_out),
    .io_zero   (_mainALU_io_zero)
  );	// src/main/scala/npc/npc.scala:41:21
  multALU pcALU (	// src/main/scala/npc/npc.scala:42:19
    .io_a      (_decoder_io_pcAluSrc ? pcReg : _gpr_io_rs1Data),	// src/main/scala/npc/npc.scala:37:20, :38:17, :40:21, :82:18
    .io_b      (_immExtender_io_immSrc),	// src/main/scala/npc/npc.scala:43:25
    .io_opcode (4'h0),
    .io_out    (_pcALU_io_out),
    .io_zero   (/* unused */)
  );	// src/main/scala/npc/npc.scala:42:19
  immExtender immExtender (	// src/main/scala/npc/npc.scala:43:25
    .io_inst    (io_inst),
    .io_immType (_decoder_io_immType),	// src/main/scala/npc/npc.scala:40:21
    .io_immSrc  (_immExtender_io_immSrc)
  );	// src/main/scala/npc/npc.scala:43:25
  finishSim finishSim (	// src/main/scala/npc/npc.scala:44:23
    .clock        (clock),
    .reset        (reset),
    .finishStatus (_decoder_io_finishIF)	// src/main/scala/npc/npc.scala:40:21
  );	// src/main/scala/npc/npc.scala:44:23
  assign io_pc = pcReg;	// src/main/scala/npc/npc.scala:14:7, :37:20
endmodule

