// Generated by CIRCT firtool-1.121.0
module singleALU(	// src/main/scala/npc/ALU/multALU.scala:9:7
  input  singleALUIO_a,	// src/main/scala/npc/ALU/multALU.scala:10:23
         singleALUIO_b,	// src/main/scala/npc/ALU/multALU.scala:10:23
         singleALUIO_cin,	// src/main/scala/npc/ALU/multALU.scala:10:23
  output singleALUIO_s,	// src/main/scala/npc/ALU/multALU.scala:10:23
         singleALUIO_cout	// src/main/scala/npc/ALU/multALU.scala:10:23
);

  wire [1:0] _singleALUIO_cout_T = {1'h0, singleALUIO_a} + {1'h0, singleALUIO_b};	// src/main/scala/npc/ALU/multALU.scala:17:35
  wire [1:0] _singleALUIO_cout_T_1 = _singleALUIO_cout_T + {1'h0, singleALUIO_cin};	// src/main/scala/npc/ALU/multALU.scala:17:35, :18:55
  assign singleALUIO_s = _singleALUIO_cout_T[0] + singleALUIO_cin;	// src/main/scala/npc/ALU/multALU.scala:9:7, :17:{35,51}
  assign singleALUIO_cout = _singleALUIO_cout_T_1[1];	// src/main/scala/npc/ALU/multALU.scala:9:7, :18:{55,74}
endmodule

