// Generated by CIRCT firtool-1.121.0
module systemDecoder(	// src/main/scala/npc/decoder/systemDecoder.scala:8:7
  input  [2:0]  io_funct3,	// src/main/scala/npc/decoder/systemDecoder.scala:9:12
  input  [3:0]  io_rs1,	// src/main/scala/npc/decoder/systemDecoder.scala:9:12
                io_rd,	// src/main/scala/npc/decoder/systemDecoder.scala:9:12
  input  [31:0] io_imm,	// src/main/scala/npc/decoder/systemDecoder.scala:9:12
  output        io_csrCrtl_csrWrite,	// src/main/scala/npc/decoder/systemDecoder.scala:9:12
  output [2:0]  io_csrCrtl_csrOpcode,	// src/main/scala/npc/decoder/systemDecoder.scala:9:12
  output        io_csrCrtl_csrRead,	// src/main/scala/npc/decoder/systemDecoder.scala:9:12
                io_csrCrtl_ebreakIF,	// src/main/scala/npc/decoder/systemDecoder.scala:9:12
                io_csrCrtl_ecallIF,	// src/main/scala/npc/decoder/systemDecoder.scala:9:12
                io_csrCrtl_mretIF	// src/main/scala/npc/decoder/systemDecoder.scala:9:12
);

  wire _io_csrCrtl_csrWrite_T_5 = io_funct3 == 3'h0;	// src/main/scala/npc/decoder/systemDecoder.scala:22:36
  assign io_csrCrtl_csrWrite =
    ~((io_funct3 == 3'h2 | io_funct3 == 3'h3) & io_rs1 == 4'h0
      | _io_csrCrtl_csrWrite_T_5);	// src/main/scala/npc/decoder/systemDecoder.scala:8:7, :22:36, :31:54, :33:{27,40,48,60,68,77,85}
  assign io_csrCrtl_csrOpcode = io_funct3;	// src/main/scala/npc/decoder/systemDecoder.scala:8:7
  assign io_csrCrtl_csrRead =
    ~(io_funct3 == 3'h1 & io_rd == 4'h0 | _io_csrCrtl_csrWrite_T_5);	// src/main/scala/npc/decoder/systemDecoder.scala:8:7, :22:36, :31:{26,38,46,54,62}
  assign io_csrCrtl_ebreakIF = _io_csrCrtl_csrWrite_T_5 & io_imm == 32'h1;	// src/main/scala/npc/decoder/systemDecoder.scala:8:7, :22:{36,44,54}
  assign io_csrCrtl_ecallIF = _io_csrCrtl_csrWrite_T_5 & io_imm == 32'h0;	// src/main/scala/npc/decoder/systemDecoder.scala:8:7, :22:36, :23:{43,53}
  assign io_csrCrtl_mretIF = _io_csrCrtl_csrWrite_T_5 & io_imm == 32'h302;	// src/main/scala/npc/decoder/systemDecoder.scala:8:7, :22:36, :24:{42,59}
endmodule

