// Generated by CIRCT firtool-1.121.0
module simpleEncodec(	// src/main/scala/codec/codec.scala:9:7
  input  [2:0] encodec_n,	// src/main/scala/codec/codec.scala:10:19
  input        encodec_en,	// src/main/scala/codec/codec.scala:10:19
  output [4:0] encodec_m	// src/main/scala/codec/codec.scala:10:19
);

  wire [7:0] _encodec_m_T = 8'h1 << encodec_n;	// src/main/scala/codec/codec.scala:15:37
  assign encodec_m = encodec_en ? _encodec_m_T[4:0] : 5'h0;	// src/main/scala/codec/codec.scala:9:7, :15:{19,37}
endmodule

module simpleDecodec(	// src/main/scala/codec/codec.scala:19:7
  input  [4:0] decodec_m,	// src/main/scala/codec/codec.scala:20:19
  input        decodec_en,	// src/main/scala/codec/codec.scala:20:19
  output [2:0] decodec_n	// src/main/scala/codec/codec.scala:20:19
);

  assign decodec_n =
    ~decodec_en | decodec_m[0]
      ? 3'h0
      : decodec_m[1] ? 3'h1 : decodec_m[2] ? 3'h2 : decodec_m[3] ? 3'h3 : 3'h4;	// src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:48:45, src/main/scala/codec/codec.scala:19:7, :25:19
endmodule

module codecTop(	// src/main/scala/codec/codec.scala:29:7
  input        clock,	// src/main/scala/codec/codec.scala:29:7
               reset,	// src/main/scala/codec/codec.scala:29:7
  input  [2:0] encodeIO_n,	// src/main/scala/codec/codec.scala:30:20
  input        encodeIO_en,	// src/main/scala/codec/codec.scala:30:20
  output [4:0] encodeIO_m,	// src/main/scala/codec/codec.scala:30:20
  input  [4:0] decodeIO_m,	// src/main/scala/codec/codec.scala:41:18
  input        decodeIO_en,	// src/main/scala/codec/codec.scala:41:18
  output [2:0] decodeIO_n	// src/main/scala/codec/codec.scala:41:18
);

  simpleEncodec simpleEncodec (	// src/main/scala/codec/codec.scala:36:29
    .encodec_n  (encodeIO_n > 3'h4 ? 3'h0 : encodeIO_n),	// src/main/scala/codec/codec.scala:37:{33,45}
    .encodec_en (encodeIO_en),
    .encodec_m  (encodeIO_m)
  );	// src/main/scala/codec/codec.scala:36:29
  simpleDecodec simpleDecodec (	// src/main/scala/codec/codec.scala:47:27
    .decodec_m  (decodeIO_m),
    .decodec_en (decodeIO_en),
    .decodec_n  (decodeIO_n)
  );	// src/main/scala/codec/codec.scala:47:27
endmodule

