// Generated by CIRCT firtool-1.121.0
module helloLED1(	// src/main/scala/helloChisel/helloChisel.scala:8:7
  input  ledIO_ledInput,	// src/main/scala/helloChisel/helloChisel.scala:9:15
  output ledIO_ledOutput	// src/main/scala/helloChisel/helloChisel.scala:9:15
);

  assign ledIO_ledOutput = ledIO_ledInput;	// src/main/scala/helloChisel/helloChisel.scala:8:7
endmodule

module helloLED2(	// src/main/scala/helloChisel/helloChisel.scala:17:7
  input  ledIO_ledInput,	// src/main/scala/helloChisel/helloChisel.scala:18:15
  output ledIO_ledOutput	// src/main/scala/helloChisel/helloChisel.scala:18:15
);

  assign ledIO_ledOutput = ledIO_ledInput;	// src/main/scala/helloChisel/helloChisel.scala:17:7
endmodule

module helloChiselTop(	// src/main/scala/helloChisel/helloChisel.scala:25:7
  input         clock,	// src/main/scala/helloChisel/helloChisel.scala:25:7
                reset,	// src/main/scala/helloChisel/helloChisel.scala:25:7
  output        io_led1Output,	// src/main/scala/helloChisel/helloChisel.scala:26:12
                io_led2Output,	// src/main/scala/helloChisel/helloChisel.scala:26:12
  output [15:0] io_counterValue	// src/main/scala/helloChisel/helloChisel.scala:26:12
);

  wire        _helloLED1_ledIO_ledOutput;	// src/main/scala/helloChisel/helloChisel.scala:32:23
  reg  [15:0] currentCountValue;	// src/main/scala/helloChisel/helloChisel.scala:39:34
  reg         ledWire;	// src/main/scala/helloChisel/helloChisel.scala:40:24
  always @(posedge clock) begin	// src/main/scala/helloChisel/helloChisel.scala:25:7
    if (reset) begin	// src/main/scala/helloChisel/helloChisel.scala:25:7
      currentCountValue <= 16'h0;	// src/main/scala/helloChisel/helloChisel.scala:39:34
      ledWire <= 1'h0;	// src/main/scala/helloChisel/helloChisel.scala:40:24
    end
    else begin	// src/main/scala/helloChisel/helloChisel.scala:25:7
      automatic logic _GEN = currentCountValue == 16'h1388;	// src/main/scala/helloChisel/helloChisel.scala:39:34, :48:26
      currentCountValue <= _GEN ? 16'h0 : currentCountValue + 16'h1;	// src/main/scala/helloChisel/helloChisel.scala:39:34, :48:{26,47}, :50:23, :52:{23,44}
      ledWire <= _GEN ^ ledWire;	// src/main/scala/helloChisel/helloChisel.scala:40:24, :48:{26,47}, :49:13
    end
  end // always @(posedge)
  helloLED1 helloLED1 (	// src/main/scala/helloChisel/helloChisel.scala:32:23
    .ledIO_ledInput  (ledWire),	// src/main/scala/helloChisel/helloChisel.scala:40:24
    .ledIO_ledOutput (_helloLED1_ledIO_ledOutput)
  );	// src/main/scala/helloChisel/helloChisel.scala:32:23
  helloLED2 helloLED2 (	// src/main/scala/helloChisel/helloChisel.scala:33:23
    .ledIO_ledInput  (_helloLED1_ledIO_ledOutput),	// src/main/scala/helloChisel/helloChisel.scala:32:23
    .ledIO_ledOutput (io_led2Output)
  );	// src/main/scala/helloChisel/helloChisel.scala:33:23
  assign io_led1Output = _helloLED1_ledIO_ledOutput;	// src/main/scala/helloChisel/helloChisel.scala:25:7, :32:23
  assign io_counterValue = currentCountValue;	// src/main/scala/helloChisel/helloChisel.scala:25:7, :39:34
endmodule

