// Generated by CIRCT firtool-1.121.0
module regGroup(	// src/main/scala/npc/regGroup/regGroup.scala:6:7
  input         clock,	// src/main/scala/npc/regGroup/regGroup.scala:6:7
                reset,	// src/main/scala/npc/regGroup/regGroup.scala:6:7
  input  [4:0]  io_rs1,	// src/main/scala/npc/regGroup/regGroup.scala:7:12
                io_rd,	// src/main/scala/npc/regGroup/regGroup.scala:7:12
  input  [31:0] io_writeData,	// src/main/scala/npc/regGroup/regGroup.scala:7:12
  input         io_writeEnable,	// src/main/scala/npc/regGroup/regGroup.scala:7:12
  output [31:0] io_rs1Data	// src/main/scala/npc/regGroup/regGroup.scala:7:12
);

  reg  [31:0]       regGroup_0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_1;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_2;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_3;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_4;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_5;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_6;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_7;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_8;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_9;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_10;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_11;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_12;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_13;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_14;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_15;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_16;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_17;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_18;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_19;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_20;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_21;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_22;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_23;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_24;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_25;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_26;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_27;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_28;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_29;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_30;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  reg  [31:0]       regGroup_31;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
  wire [31:0][31:0] _GEN =
    {{regGroup_31},
     {regGroup_30},
     {regGroup_29},
     {regGroup_28},
     {regGroup_27},
     {regGroup_26},
     {regGroup_25},
     {regGroup_24},
     {regGroup_23},
     {regGroup_22},
     {regGroup_21},
     {regGroup_20},
     {regGroup_19},
     {regGroup_18},
     {regGroup_17},
     {regGroup_16},
     {regGroup_15},
     {regGroup_14},
     {regGroup_13},
     {regGroup_12},
     {regGroup_11},
     {regGroup_10},
     {regGroup_9},
     {regGroup_8},
     {regGroup_7},
     {regGroup_6},
     {regGroup_5},
     {regGroup_4},
     {regGroup_3},
     {regGroup_2},
     {regGroup_1},
     {regGroup_0}};	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :26:13
  always @(posedge clock) begin	// src/main/scala/npc/regGroup/regGroup.scala:6:7
    if (reset) begin	// src/main/scala/npc/regGroup/regGroup.scala:6:7
      regGroup_0 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_1 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_2 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_3 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_4 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_5 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_6 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_7 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_8 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_9 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_10 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_11 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_12 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_13 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_14 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_15 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_16 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_17 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_18 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_19 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_20 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_21 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_22 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_23 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_24 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_25 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_26 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_27 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_28 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_29 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_30 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      regGroup_31 <= 32'h0;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
    end
    else begin	// src/main/scala/npc/regGroup/regGroup.scala:6:7
      automatic logic _GEN_0 = (|io_rd) & io_writeEnable;	// src/main/scala/npc/regGroup/regGroup.scala:21:{13,20}
      if (_GEN_0 & ~(|io_rd))	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{13,20,44}, :22:20
        regGroup_0 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h1)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_1 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h2)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_2 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h3)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_3 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h4)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_4 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h5)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_5 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h6)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_6 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h7)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_7 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h8)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_8 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h9)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_9 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'hA)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_10 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'hB)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_11 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'hC)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_12 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'hD)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_13 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'hE)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_14 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'hF)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_15 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h10)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_16 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h11)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_17 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h12)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_18 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h13)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_19 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h14)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_20 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h15)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_21 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h16)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_22 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h17)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_23 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h18)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_24 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h19)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_25 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h1A)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_26 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h1B)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_27 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h1C)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_28 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h1D)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_29 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & io_rd == 5'h1E)	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_30 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
      if (_GEN_0 & (&io_rd))	// src/main/scala/npc/regGroup/regGroup.scala:19:25, :21:{20,44}, :22:20
        regGroup_31 <= io_writeData;	// src/main/scala/npc/regGroup/regGroup.scala:19:25
    end
  end // always @(posedge)
  assign io_rs1Data = _GEN[io_rs1];	// src/main/scala/npc/regGroup/regGroup.scala:6:7, :26:13
endmodule


// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module npc(	// src/main/scala/npc/npc.scala:14:7
  input         clock,	// src/main/scala/npc/npc.scala:14:7
                reset,	// src/main/scala/npc/npc.scala:14:7
  output [31:0] io_readAddr,	// src/main/scala/npc/npc.scala:25:12
  input  [31:0] io_readData,	// src/main/scala/npc/npc.scala:25:12
  output [31:0] io_writeAddr,	// src/main/scala/npc/npc.scala:25:12
                io_writeData,	// src/main/scala/npc/npc.scala:25:12
  output        io_writeEnable,	// src/main/scala/npc/npc.scala:25:12
  output [31:0] io_pc,	// src/main/scala/npc/npc.scala:25:12
  input  [31:0] io_inst	// src/main/scala/npc/npc.scala:25:12
);

  wire [31:0] _gpr_io_rs1Data;	// src/main/scala/npc/npc.scala:40:17
  reg  [31:0] pcReg;	// src/main/scala/npc/npc.scala:39:20
  wire        _imm_T_22 = io_inst[6:0] == 7'h6F;	// src/main/scala/npc/npc.scala:22:44, :43:21
  wire        _imm_T_18 = io_inst[6:0] == 7'h37;	// src/main/scala/npc/npc.scala:22:69, :43:21
  wire [1:0]  funct3 =
    _imm_T_22 | _imm_T_18 | io_inst[6:0] == 7'h17 ? 2'h0 : io_inst[14:13];	// src/main/scala/npc/npc.scala:22:{44,60,69,85,94}, :43:21, :44:{17,43}
  wire        _imm_T = io_inst[6:0] == 7'h13;	// src/main/scala/npc/npc.scala:23:113, :43:21
  wire [20:0] _imm_T_29 =
    _imm_T_22 ? {io_inst[31], io_inst[19:12], io_inst[20], io_inst[30:21], 1'h0} : 21'h0;	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/npc.scala:18:36, :20:{31,45,57,66}, :22:44
  wire [19:0] _GEN = {20{io_inst[31]}};	// src/main/scala/chisel3/util/Mux.scala:126:16
  wire        gpr_io_writeEnable =
    {io_inst[6:0],
     funct3,
     io_inst[6:0] == 7'h73 | io_inst[6:0] == 7'h33 | _imm_T & funct3 == 2'h1
       ? io_inst[31:25]
       : 7'h0} == 16'h2600;	// src/main/scala/npc/npc.scala:23:{59,75,85,102,113,130,141}, :43:21, :44:17, :45:{17,50}, :69:{13,36}
  wire [31:0] gpr_io_writeData =
    gpr_io_writeEnable
      ? _gpr_io_rs1Data
        + (_imm_T | io_inst[6:0] == 7'h3
             ? {_GEN, io_inst[31:20]}
             : io_inst[6:0] == 7'h23
                 ? {_GEN, io_inst[31:25], io_inst[11:7]}
                 : io_inst[6:0] == 7'h63
                     ? {{20{io_inst[31]}},
                        io_inst[7],
                        io_inst[30:25],
                        io_inst[11:8],
                        1'h0}
                     : _imm_T_18
                         ? {io_inst[31:12], 12'h0}
                         : {{11{_imm_T_29[20]}}, _imm_T_29})
      : 32'h0;	// src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/npc.scala:16:32, :18:{36,45,53,65}, :19:{31,36}, :22:69, :23:113, :40:17, :43:21, :45:50, :48:21, :50:19, :61:13, :62:13, :63:13, :69:36, :71:{23,37}
  `ifndef SYNTHESIS	// src/main/scala/npc/npc.scala:88:9
    always @(posedge clock) begin	// src/main/scala/npc/npc.scala:88:9
      if ((`PRINTF_COND_) & ~reset) begin	// src/main/scala/npc/npc.scala:88:9, :89:9
        $fwrite(32'h80000002, "pc = 0x%x inst = 0x%x\n", pcReg, io_inst);	// src/main/scala/npc/npc.scala:39:20, :88:9
        $fwrite(32'h80000002, "writeTarget = %d writeData = 0x%x writeEnable = %d\n",
                io_inst[11:7], gpr_io_writeData, gpr_io_writeEnable);	// src/main/scala/npc/npc.scala:48:21, :50:19, :69:36, :71:23, :89:9
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// src/main/scala/npc/npc.scala:14:7
    if (reset)	// src/main/scala/npc/npc.scala:14:7
      pcReg <= 32'h80000000;	// src/main/scala/npc/npc.scala:39:20
    else	// src/main/scala/npc/npc.scala:14:7
      pcReg <= pcReg + 32'h4;	// src/main/scala/npc/npc.scala:39:20, :87:15
  end // always @(posedge)
  regGroup gpr (	// src/main/scala/npc/npc.scala:40:17
    .clock          (clock),
    .reset          (reset),
    .io_rs1         (io_inst[19:15]),	// src/main/scala/npc/npc.scala:51:22
    .io_rd          (io_inst[11:7]),	// src/main/scala/npc/npc.scala:48:21
    .io_writeData   (gpr_io_writeData),	// src/main/scala/npc/npc.scala:50:19, :69:36, :71:23
    .io_writeEnable (gpr_io_writeEnable),	// src/main/scala/npc/npc.scala:69:36
    .io_rs1Data     (_gpr_io_rs1Data)
  );	// src/main/scala/npc/npc.scala:40:17
  assign io_readAddr = 32'h0;	// src/main/scala/npc/npc.scala:14:7
  assign io_writeAddr = 32'h0;	// src/main/scala/npc/npc.scala:14:7
  assign io_writeData = 32'h0;	// src/main/scala/npc/npc.scala:14:7
  assign io_writeEnable = 1'h0;	// src/main/scala/npc/npc.scala:14:7
  assign io_pc = pcReg;	// src/main/scala/npc/npc.scala:14:7, :39:20
endmodule

