// Generated by CIRCT firtool-1.121.0
module ps2Codec(	// src/main/scala/PS2/PS2Connecter.scala:7:7
  input  [7:0] codecIO_inputValue,	// src/main/scala/PS2/PS2Connecter.scala:9:19
  output [7:0] codecIO_outputValue	// src/main/scala/PS2/PS2Connecter.scala:9:19
);

  assign codecIO_outputValue =
    codecIO_inputValue == 8'h46
      ? 8'h39
      : codecIO_inputValue == 8'h2B
          ? 8'h66
          : codecIO_inputValue == 8'h1C
              ? 8'h61
              : codecIO_inputValue == 8'h26
                  ? 8'h33
                  : codecIO_inputValue == 8'h1E
                      ? 8'h32
                      : codecIO_inputValue == 8'hF0
                          ? 8'h3F
                          : codecIO_inputValue == 8'h23
                              ? 8'h64
                              : codecIO_inputValue == 8'h2E
                                  ? 8'h35
                                  : codecIO_inputValue == 8'h45
                                      ? 8'h30
                                      : codecIO_inputValue == 8'h3D
                                          ? 8'h37
                                          : codecIO_inputValue == 8'h32
                                              ? 8'h62
                                              : codecIO_inputValue == 8'h16
                                                  ? 8'h31
                                                  : codecIO_inputValue == 8'h21
                                                      ? 8'h63
                                                      : codecIO_inputValue == 8'h3E
                                                          ? 8'h38
                                                          : codecIO_inputValue == 8'h36
                                                              ? 8'h36
                                                              : codecIO_inputValue == 8'h24
                                                                  ? 8'h65
                                                                  : codecIO_inputValue == 8'h25
                                                                      ? 8'h34
                                                                      : 8'h0;	// src/main/scala/PS2/PS2Connecter.scala:7:7, :38:25, src/main/scala/chisel3/util/Mux.scala:126:16
endmodule

module ps2Receiver(	// src/main/scala/PS2/PS2Connecter.scala:64:7
  input        clock,	// src/main/scala/PS2/PS2Connecter.scala:64:7
               reset,	// src/main/scala/PS2/PS2Connecter.scala:64:7
               receiverIO_din,	// src/main/scala/PS2/PS2Connecter.scala:66:20
  input  [1:0] receiverIO_clkin,	// src/main/scala/PS2/PS2Connecter.scala:66:20
  output [7:0] receiverIO_dout	// src/main/scala/PS2/PS2Connecter.scala:66:20
);

  reg [8:0] tmpOut;	// src/main/scala/PS2/PS2Connecter.scala:72:21
  reg [3:0] signalCount;	// src/main/scala/PS2/PS2Connecter.scala:74:28
  always @(posedge clock) begin	// src/main/scala/PS2/PS2Connecter.scala:64:7
    if (reset) begin	// src/main/scala/PS2/PS2Connecter.scala:64:7
      tmpOut <= 9'h0;	// src/main/scala/PS2/PS2Connecter.scala:72:21
      signalCount <= 4'h0;	// src/main/scala/PS2/PS2Connecter.scala:74:28, :81:29
    end
    else begin	// src/main/scala/PS2/PS2Connecter.scala:64:7
      automatic logic _GEN;	// src/main/scala/PS2/PS2Connecter.scala:77:24
      _GEN = receiverIO_clkin == 2'h2;	// src/main/scala/PS2/PS2Connecter.scala:77:24
      if (_GEN)	// src/main/scala/PS2/PS2Connecter.scala:77:24
        tmpOut <=
          (|signalCount) & signalCount < 4'hA ? {receiverIO_din, tmpOut[8:1]} : 9'h0;	// src/main/scala/PS2/PS2Connecter.scala:72:21, :74:28, :81:{16,29,35,50,73,82}
      if (signalCount > 4'hA)	// src/main/scala/PS2/PS2Connecter.scala:74:28, :85:19
        signalCount <= 4'h0;	// src/main/scala/PS2/PS2Connecter.scala:74:28, :81:29
      else if (_GEN)	// src/main/scala/PS2/PS2Connecter.scala:77:24
        signalCount <= signalCount + 4'h1;	// src/main/scala/PS2/PS2Connecter.scala:74:28, :79:30
    end
  end // always @(posedge)
  assign receiverIO_dout =
    tmpOut[0] + tmpOut[1] + tmpOut[2] + tmpOut[3] + tmpOut[4] + tmpOut[5] + tmpOut[6]
    + tmpOut[7] + tmpOut[8]
      ? tmpOut[7:0]
      : 8'h0;	// src/main/scala/PS2/PS2Connecter.scala:64:7, :72:21, :90:{23,33,40,46,53}
endmodule


// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module ps2Connecter(	// src/main/scala/PS2/PS2Connecter.scala:94:7
  input        clock,	// src/main/scala/PS2/PS2Connecter.scala:94:7
               reset,	// src/main/scala/PS2/PS2Connecter.scala:94:7
               io_ps2_clk,	// src/main/scala/PS2/PS2Connecter.scala:96:12
               io_ps2_data,	// src/main/scala/PS2/PS2Connecter.scala:96:12
  output [7:0] io_out	// src/main/scala/PS2/PS2Connecter.scala:96:12
);

  wire [7:0] _ps2Receiver_receiverIO_dout;	// src/main/scala/PS2/PS2Connecter.scala:104:25
  wire [7:0] _ps2Codec_codecIO_outputValue;	// src/main/scala/PS2/PS2Connecter.scala:103:22
  reg  [1:0] clkReg;	// src/main/scala/PS2/PS2Connecter.scala:105:21
  `ifndef SYNTHESIS	// src/main/scala/PS2/PS2Connecter.scala:116:11
    always @(posedge clock) begin	// src/main/scala/PS2/PS2Connecter.scala:116:11
      if ((`PRINTF_COND_) & (|_ps2Codec_codecIO_outputValue) & ~reset)	// src/main/scala/PS2/PS2Connecter.scala:103:22, :115:14, :116:11
        $fwrite(32'h80000002, "%d\n", _ps2Codec_codecIO_outputValue);	// src/main/scala/PS2/PS2Connecter.scala:103:22, :116:11
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// src/main/scala/PS2/PS2Connecter.scala:94:7
    if (reset)	// src/main/scala/PS2/PS2Connecter.scala:94:7
      clkReg <= 2'h0;	// src/main/scala/PS2/PS2Connecter.scala:105:21
    else	// src/main/scala/PS2/PS2Connecter.scala:94:7
      clkReg <= {clkReg[0], io_ps2_clk};	// src/main/scala/PS2/PS2Connecter.scala:105:21, :108:{17,21}
  end // always @(posedge)
  ps2Codec ps2Codec (	// src/main/scala/PS2/PS2Connecter.scala:103:22
    .codecIO_inputValue  (_ps2Receiver_receiverIO_dout),	// src/main/scala/PS2/PS2Connecter.scala:104:25
    .codecIO_outputValue (_ps2Codec_codecIO_outputValue)
  );	// src/main/scala/PS2/PS2Connecter.scala:103:22
  ps2Receiver ps2Receiver (	// src/main/scala/PS2/PS2Connecter.scala:104:25
    .clock            (clock),
    .reset            (reset),
    .receiverIO_din   (io_ps2_data),
    .receiverIO_clkin (clkReg),	// src/main/scala/PS2/PS2Connecter.scala:105:21
    .receiverIO_dout  (_ps2Receiver_receiverIO_dout)
  );	// src/main/scala/PS2/PS2Connecter.scala:104:25
  assign io_out = _ps2Codec_codecIO_outputValue;	// src/main/scala/PS2/PS2Connecter.scala:94:7, :103:22
endmodule

