// Generated by CIRCT firtool-1.121.0
module mux21c(	// src/main/scala/selector/selector.scala:9:7
  input  muxIO_a,	// src/main/scala/selector/selector.scala:10:15
         muxIO_b,	// src/main/scala/selector/selector.scala:10:15
         muxIO_s,	// src/main/scala/selector/selector.scala:10:15
  output muxIO_y	// src/main/scala/selector/selector.scala:10:15
);

  assign muxIO_y = muxIO_s ? muxIO_b : muxIO_a;	// src/main/scala/selector/selector.scala:9:7, :16:15
endmodule

module selectorTop(	// src/main/scala/selector/selector.scala:19:7
  input  clock,	// src/main/scala/selector/selector.scala:19:7
         reset,	// src/main/scala/selector/selector.scala:19:7
         io_a,	// src/main/scala/selector/selector.scala:20:12
         io_b,	// src/main/scala/selector/selector.scala:20:12
         io_s,	// src/main/scala/selector/selector.scala:20:12
  output io_y	// src/main/scala/selector/selector.scala:20:12
);

  mux21c mux21c (	// src/main/scala/selector/selector.scala:27:20
    .muxIO_a (io_a),
    .muxIO_b (io_b),
    .muxIO_s (io_s),
    .muxIO_y (io_y)
  );	// src/main/scala/selector/selector.scala:27:20
endmodule

