// Generated by CIRCT firtool-1.121.0
module singleALU(	// src/main/scala/singleALU/singleALU.scala:9:7
  input  singALUIO_a,	// src/main/scala/singleALU/singleALU.scala:10:19
         singALUIO_b,	// src/main/scala/singleALU/singleALU.scala:10:19
  output singALUIO_s	// src/main/scala/singleALU/singleALU.scala:10:19
);

  assign singALUIO_s = singALUIO_a + singALUIO_b;	// src/main/scala/singleALU/singleALU.scala:9:7, :16:28
endmodule

module singleALUTop(	// src/main/scala/singleALU/singleALU.scala:21:7
  input  clock,	// src/main/scala/singleALU/singleALU.scala:21:7
         reset,	// src/main/scala/singleALU/singleALU.scala:21:7
         io_a,	// src/main/scala/singleALU/singleALU.scala:22:12
         io_b,	// src/main/scala/singleALU/singleALU.scala:22:12
  output io_s,	// src/main/scala/singleALU/singleALU.scala:22:12
         io_c	// src/main/scala/singleALU/singleALU.scala:22:12
);

  singleALU singleALU (	// src/main/scala/singleALU/singleALU.scala:29:23
    .singALUIO_a (io_a),
    .singALUIO_b (io_b),
    .singALUIO_s (io_s)
  );	// src/main/scala/singleALU/singleALU.scala:29:23
  assign io_c = 1'h0;	// src/main/scala/singleALU/singleALU.scala:21:7, :29:23
endmodule

