// Generated by CIRCT firtool-1.121.0
module normalLED(	// src/main/scala/streamingLight/streamingLight.scala:9:7
  input  ledIO_ledInput,	// src/main/scala/streamingLight/streamingLight.scala:10:15
  output ledIO_ledOutput	// src/main/scala/streamingLight/streamingLight.scala:10:15
);

  assign ledIO_ledOutput = ledIO_ledInput;	// src/main/scala/streamingLight/streamingLight.scala:9:7
endmodule

module streamingLightTop(	// src/main/scala/streamingLight/streamingLight.scala:17:7
  input        clock,	// src/main/scala/streamingLight/streamingLight.scala:17:7
               reset,	// src/main/scala/streamingLight/streamingLight.scala:17:7
  output [7:0] io_ledOutputGroup,	// src/main/scala/streamingLight/streamingLight.scala:19:12
               io_ledLineStatusOutput	// src/main/scala/streamingLight/streamingLight.scala:19:12
);

  wire       _leds_7_ledIO_ledOutput;	// src/main/scala/streamingLight/streamingLight.scala:27:13
  wire       _leds_6_ledIO_ledOutput;	// src/main/scala/streamingLight/streamingLight.scala:27:13
  wire       _leds_5_ledIO_ledOutput;	// src/main/scala/streamingLight/streamingLight.scala:27:13
  wire       _leds_4_ledIO_ledOutput;	// src/main/scala/streamingLight/streamingLight.scala:27:13
  wire       _leds_3_ledIO_ledOutput;	// src/main/scala/streamingLight/streamingLight.scala:27:13
  wire       _leds_2_ledIO_ledOutput;	// src/main/scala/streamingLight/streamingLight.scala:27:13
  wire       _leds_1_ledIO_ledOutput;	// src/main/scala/streamingLight/streamingLight.scala:27:13
  wire       _leds_0_ledIO_ledOutput;	// src/main/scala/streamingLight/streamingLight.scala:27:13
  reg  [7:0] ledLineStatus;	// src/main/scala/streamingLight/streamingLight.scala:25:28
  always @(posedge clock) begin	// src/main/scala/streamingLight/streamingLight.scala:17:7
    if (reset)	// src/main/scala/streamingLight/streamingLight.scala:17:7
      ledLineStatus <= 8'h1;	// src/main/scala/streamingLight/streamingLight.scala:25:28
    else	// src/main/scala/streamingLight/streamingLight.scala:17:7
      ledLineStatus <= {ledLineStatus[6:0], ledLineStatus[7]};	// src/main/scala/streamingLight/streamingLight.scala:25:28, :40:44
  end // always @(posedge)
  normalLED leds_0 (	// src/main/scala/streamingLight/streamingLight.scala:27:13
    .ledIO_ledInput  (ledLineStatus[0]),	// src/main/scala/streamingLight/streamingLight.scala:25:28, :34:42
    .ledIO_ledOutput (_leds_0_ledIO_ledOutput)
  );	// src/main/scala/streamingLight/streamingLight.scala:27:13
  normalLED leds_1 (	// src/main/scala/streamingLight/streamingLight.scala:27:13
    .ledIO_ledInput  (ledLineStatus[1]),	// src/main/scala/streamingLight/streamingLight.scala:25:28, :34:42
    .ledIO_ledOutput (_leds_1_ledIO_ledOutput)
  );	// src/main/scala/streamingLight/streamingLight.scala:27:13
  normalLED leds_2 (	// src/main/scala/streamingLight/streamingLight.scala:27:13
    .ledIO_ledInput  (ledLineStatus[2]),	// src/main/scala/streamingLight/streamingLight.scala:25:28, :34:42
    .ledIO_ledOutput (_leds_2_ledIO_ledOutput)
  );	// src/main/scala/streamingLight/streamingLight.scala:27:13
  normalLED leds_3 (	// src/main/scala/streamingLight/streamingLight.scala:27:13
    .ledIO_ledInput  (ledLineStatus[3]),	// src/main/scala/streamingLight/streamingLight.scala:25:28, :34:42
    .ledIO_ledOutput (_leds_3_ledIO_ledOutput)
  );	// src/main/scala/streamingLight/streamingLight.scala:27:13
  normalLED leds_4 (	// src/main/scala/streamingLight/streamingLight.scala:27:13
    .ledIO_ledInput  (ledLineStatus[4]),	// src/main/scala/streamingLight/streamingLight.scala:25:28, :34:42
    .ledIO_ledOutput (_leds_4_ledIO_ledOutput)
  );	// src/main/scala/streamingLight/streamingLight.scala:27:13
  normalLED leds_5 (	// src/main/scala/streamingLight/streamingLight.scala:27:13
    .ledIO_ledInput  (ledLineStatus[5]),	// src/main/scala/streamingLight/streamingLight.scala:25:28, :34:42
    .ledIO_ledOutput (_leds_5_ledIO_ledOutput)
  );	// src/main/scala/streamingLight/streamingLight.scala:27:13
  normalLED leds_6 (	// src/main/scala/streamingLight/streamingLight.scala:27:13
    .ledIO_ledInput  (ledLineStatus[6]),	// src/main/scala/streamingLight/streamingLight.scala:25:28, :34:42
    .ledIO_ledOutput (_leds_6_ledIO_ledOutput)
  );	// src/main/scala/streamingLight/streamingLight.scala:27:13
  normalLED leds_7 (	// src/main/scala/streamingLight/streamingLight.scala:27:13
    .ledIO_ledInput  (ledLineStatus[7]),	// src/main/scala/streamingLight/streamingLight.scala:25:28, :34:42
    .ledIO_ledOutput (_leds_7_ledIO_ledOutput)
  );	// src/main/scala/streamingLight/streamingLight.scala:27:13
  assign io_ledOutputGroup =
    {_leds_7_ledIO_ledOutput,
     _leds_6_ledIO_ledOutput,
     _leds_5_ledIO_ledOutput,
     _leds_4_ledIO_ledOutput,
     _leds_3_ledIO_ledOutput,
     _leds_2_ledIO_ledOutput,
     _leds_1_ledIO_ledOutput,
     _leds_0_ledIO_ledOutput};	// src/main/scala/streamingLight/streamingLight.scala:17:7, :27:13, :37:25
  assign io_ledLineStatusOutput = ledLineStatus;	// src/main/scala/streamingLight/streamingLight.scala:17:7, :25:28
endmodule

